spring:
  docker:
    compose:
      file: src/docker/docker-compose-local.yaml
  autoconfigure:
    exclude:
      - org.springframework.ai.model.google.genai.autoconfigure.chat.GoogleGenAiChatAutoConfiguration
      - org.springframework.ai.model.google.genai.autoconfigure.embedding.GoogleGenAiEmbeddingConnectionAutoConfiguration
      - org.springframework.ai.model.google.genai.autoconfigure.embedding.GoogleGenAiTextEmbeddingAutoConfiguration
      - org.springframework.ai.model.anthropic.autoconfigure.AnthropicChatAutoConfiguration
      - org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2:3b
          temperature: 0.3
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8100
        tenant-name: nexus-tenant
        database-name: nexus-database
        collection-name: nexus-docs
        initialize-schema: true

logging:
  level:
    org.springframework.ai: DEBUG